name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "cloudmail-db"
database_id = "65a691e5-a619-435d-866f-8891ee1bb83f"

[[kv_namespaces]]
binding = "kv"
id = "22e82199df0b4d2c962eb14eaa71367b"

[[r2_buckets]]
binding = "r2"
bucket_name = "cloudmail-r2"

[ai]
binding = "ai"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 * * * *"]

[vars]
#ai_model = ""
#analysis_cache = false
#orm_log = false
#domain = []
#admin = ""
#jwt_secret = ""

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
